--- # Add packages that I use on my Fedora workstation, requires the installation of ansible and starting of openssh-server before it can actually be run
- name: "Local configuration with ansible"
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: "Enable fedora-cisco-openh264 for totem"
    dnf:
      enablerepo: fedora-cisco-openh264
      name:
        - gstreamer1-plugin-openh264
        - mozilla-openh264
      state: latest
  - name: "install software development tools"
    dnf:
      name: 
      - vim-enhanced
      - git
      state: latest
  - name: "install games"
    dnf:
      name:
      - steam
  - name: "install graphics tools"
    dnf: 
      name: 
        - krita
        - blender
        - gimp
        - inkscape
        - avidemux
        - rapid-photo-downloader
      state: latest
  - name: "install audio applications"
    dnf:
      name:
        - audacity
        - hydrogen
        - soundkonverter
        - pavucontrol
      state: latest
  - name: "install sysadmin tools"
    dnf:
      name: 
        - x2goclient
        - remmina
        - seahorse
        - perl-YUM-RepoQuery
        - etckeeper-dnf
        - virt-manager
        - snapd
        - xrdp
        - openconnect
        - NetworkManager-openconnect-gnome
        - pyhoca-gui
        - pyhoca-cli
        - wireshark
        - inxi
        - apg
      state: latest
  - name: "install backup applications"
    dnf:
      name:
        - restic
      state: latest
  - name: "packages needed to watch LinuxAcademy videos in Firefox."
    dnf:
      name:
        ffmpeg-libs
      state: latest
  - name: "install packages for office and desktop publishing"
    dnf:
      name:
        - scribus
      state: latest
  - name: "install security tools"
    dnf:
      name: 
        - 'https://spideroak.com/dist/encryptr/signed/linux/rpm/encryptr-2.0.0-1.x86_64.rpm'
      state: latest
  - name: "install communications tools"
    dnf:
      name:
        - telegram-desktop
        - 'https://downloads.slack-edge.com/linux_releases/slack-4.3.2-0.1.fc21.x86_64.rpm'
      state: latest
      #    snap:
      # name:
      #   - slack
      # state: present
  - name: "install multimedia processing packages"
    dnf:
      name: 
        - HandBrake-gui
        - youtube-dl
        - 'https://dl.google.com/linux/direct/google-musicmanager-beta_current_x86_64.rpm'
        - obs-studio
      state: latest
  - name: "install additional browsers"
    dnf:
      name:
       # - chromium
        - chromium-libs-media-freeworld
      state: latest
