--- # Add packages that I use on my Fedora workstation, requires the installation of ansible and starting of openssh-server before it can actually be run
- name: "Local configuration with ansible"
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: "Enable fedora-cisco-openh264 for totem"
    dnf:
      enablerepo: fedora-cisco-openh264
      name:
        - gstreamer1-plugin-openh264
        - mozilla-openh264
      state: latest
  - name: "install software development tools"
    dnf:
      name: 
      - vim-enhanced
      - git
      - icedtea-web
      - java-1.8.0-openjdk-headless
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
      - kernel-devel
      state: latest
  - name: "install games"
    dnf:
      name:
      - steam
  - name: "install graphics tools"
    dnf: 
      name: 
        - krita
          #  - blender
        - gimp
        - inkscape
        - avidemux
        - rapid-photo-downloader
        - hplip-gui
        - jp2a
        - asciio
      state: latest
  - name: "Create /snap symlink on Fedora to allow classic confinement snaps to install"
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link
    when: ansible_distribution == 'Fedora'

  - name: "install blender via snap package"
    snap:
      name: blender
      state: present
      channel: stable
      classic: yes
  - name: "install audio applications"
    dnf:
      name:
        - audacity
        - hydrogen
        - soundkonverter
        - pavucontrol
        - pithos
      state: latest
  - name: "install pulseaudio-module-bluetooth-freeworld for aptx support"
    command: "dnf install -y pulseaudio-module-bluetooth-freeworld --allowerasing"
      # With Ansible 2.10 allowerasing is a builtin
      #    dnf:
      #name:
      #  - pulseaudio-module-bluetooth-freeworld
      #state: latest
      #allowerasing: yes
  - name: "install sysadmin tools"
    dnf:
      name: 
        - x2goclient
        - remmina
        - seahorse
        - perl-YUM-RepoQuery
        - etckeeper-dnf
        - virt-manager
        - snapd
        - xrdp
        - openconnect
        - nmap
        - NetworkManager-openconnect-gnome
        - pyhoca-gui
        - pyhoca-cli
        - wireshark
        - inxi
        - apg
        - rpmconf
        - nfs4-acl-tools
        - sysstat
        - smem
        - exfat-utils
        - fuse-exfat
        - hdparm
        - fio
        - meld
        - smartmontools
        - fdupes
        - lshw
        - python3-ansible-lint
        - ansible
      state: latest
  - name: "install backup applications"
    dnf:
      name:
        - restic
      state: latest
  - name: "packages needed to watch LinuxAcademy videos in Firefox."
    dnf:
      name:
        ffmpeg-libs
      state: latest
  - name: "install packages for office and desktop publishing"
    dnf:
      name:
        - scribus
      state: latest
  - name: "install security tools"
    dnf:
      name: 
        - 'https://spideroak.com/dist/encryptr/signed/linux/rpm/encryptr-2.0.0-1.x86_64.rpm'
      state: latest
  - name: "install communications tools"
    dnf:
      name:
        - telegram-desktop
        - 'https://downloads.slack-edge.com/linux_releases/slack-4.3.2-0.1.fc21.x86_64.rpm'
        - hexchat
        - 'https://packages.microsoft.com/yumrepos/ms-teams/teams-1.3.00.16851-1.x86_64.rpm'
      state: latest
      #    snap:
      # name:
      #   - slack
      # state: present
  - name: "install multimedia processing packages"
    dnf:
      name: 
        - HandBrake-gui
        - youtube-dl
        - 'https://dl.google.com/linux/direct/google-musicmanager-beta_current_x86_64.rpm'
        - obs-studio
      state: latest
  - name: "install additional browsers"
    dnf:
      name:
       # - chromium
       # - chromium-libs-media-freeworld
        - chromium-freeworld
      state: latest
